modLoader="javafml"
loaderVersion="[47,)"
license="AGPL-3.0-or-later"
issueTrackerURL="https://github.com/better-content/oc2r-wireless-pubsub/issues"
displayURL="https://github.com/better-content/oc2r-wireless-pubsub"
logoFile=""
authors="oc2r_wireless_pubsub"
credits=""
displayName="${mod_name}"
version="${mod_version}"
description="A Forge 1.20.1 mod scaffold."

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description="A Forge 1.20.1 mod scaffold."
authors="oc2r_wireless_pubsub"

[[dependencies.oc2r_wireless_pubsub]]
modId="minecraft"
mandatory=true
versionRange="[${mc_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.oc2r_wireless_pubsub]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.oc2r_wireless_pubsub]]
modId="oc2r"
mandatory=true
versionRange="[2.1.0,)"
ordering="AFTER"
side="BOTH"
